on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Run Makefile
        run: make VERSION=${GITHUB_REF#refs/tags/} clean archive
