on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Run Makefile
        run: make VERSION=${GITHUB_REF#refs/tags/} clean archive
      - name: Publish to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: s3://epi-repository/release/monitoring-plugins/epimorphics/monitoring-plugins-aws/
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-1'
          SOURCE_DIR: 'release'
