on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from tag
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');
      - name: Echo
        run: echo 
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run Makefile
        run: make VERSION=${{ steps.tag.outputs.result }} clean archive
